### ISSUE TITLE
Ability to disable various autolinks

### ISSUE THREAD

**Issue by jasonrhodes** [bigboringsystem/twitter-text#1]
We definitely want the ability to turn off auto hashtag linking, from bigboringsystem/bigboringsystem#187

Do we just want to make it possible to disable the auto @mention twitter linking, too? Or to pass in functions to control the replacement, like if you wanted @<user> to link to a BBS profile (I know that's not possible with the UID profile link but, just an example)? Probably overkill right now, but :shrug:

**Comment by imakewebthings** [comment]
@jasonrhodes It's already possible to change where all the entities link to in options (see near https://github.com/twitter/twitter-text/blob/0b2968b4426a3416f89c7ed9c23bf13f8345beca/js/twitter-text.js#L674). The regular expressions for matching a "hashtag" character and all other entity identifiers are also options, so we could change "hashtags" to be words that start with the shrug ascii if we were so inclined.

What doesn't exist is disabling any given entity type wholesale. I'm down for adding flags for all of them.
