### ISSUE TITLE
Remove non-JS to streamline code

### ISSUE THREAD

**Issue by jasonrhodes** [bigboringsystem/twitter-text#2]
We're going to add features and changes to this repo but we're not going to update anything but the JS, so we might as well jettison those parts, eh?

**Comment by imakewebthings** [comment]
I'm a little concerned about the potential for conflicts when doing upstream pulls from Twitter. Are my fears unfounded?

**Comment by imakewebthings** [comment]
Welp, this is happening because Twitter keeps the package.json in the subdirectory, making git URL installs of our version from BBS's package.json impossible.
